--------------------------------------------------------
--  File created - Sunday-November-15-2015   
--------------------------------------------------------
DROP TABLE "SCHOOL"."TBL_ADDRESS" cascade constraints;
DROP TABLE "SCHOOL"."TBL_ATTND_CLNDR" cascade constraints;
DROP TABLE "SCHOOL"."TBL_CERTIFICATE" cascade constraints;
DROP TABLE "SCHOOL"."TBL_CERTI_FIELDS" cascade constraints;
DROP TABLE "SCHOOL"."TBL_CERTI_FIELDS_RELN" cascade constraints;
DROP TABLE "SCHOOL"."TBL_CERTI_FIELD_VALUES" cascade constraints;
DROP TABLE "SCHOOL"."TBL_CLASS_SUB_RELN" cascade constraints;
DROP TABLE "SCHOOL"."TBL_STD_ACA_PERF_HIST" cascade constraints;
DROP TABLE "SCHOOL"."TBL_STD_ATTND" cascade constraints;
DROP TABLE "SCHOOL"."TBL_STD_CURR_STD" cascade constraints;
DROP TABLE "SCHOOL"."TBL_STD_CURR_STD_PERF" cascade constraints;
DROP TABLE "SCHOOL"."TBL_STUDENT" cascade constraints;
DROP SEQUENCE "SCHOOL"."SEQ_ATTND_CLNDR";
DROP SEQUENCE "SCHOOL"."SEQ_CERTIFICATE";
DROP SEQUENCE "SCHOOL"."SEQ_CERTI_FIELDS";
DROP SEQUENCE "SCHOOL"."SEQ_CERTI_FIELDS_RELN";
DROP SEQUENCE "SCHOOL"."SEQ_CERTI_FIELD_VALUES";
DROP SEQUENCE "SCHOOL"."SEQ_STD_ACA_PERF_HIST";
DROP SEQUENCE "SCHOOL"."SEQ_STD_ATTND";
DROP SEQUENCE "SCHOOL"."SEQ_STD_CURR_STD";
DROP SEQUENCE "SCHOOL"."SEQ_STD_CURR_STD_PERF";
DROP SEQUENCE "SCHOOL"."SEQ_STUDENT";
DROP PROCEDURE "SCHOOL"."GEN_ROLL_NO";
--------------------------------------------------------
--  DDL for Sequence SEQ_ATTND_CLNDR
--------------------------------------------------------

   CREATE SEQUENCE  "SCHOOL"."SEQ_ATTND_CLNDR"  MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SEQ_CERTIFICATE
--------------------------------------------------------

   CREATE SEQUENCE  "SCHOOL"."SEQ_CERTIFICATE"  MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SEQ_CERTI_FIELDS
--------------------------------------------------------

   CREATE SEQUENCE  "SCHOOL"."SEQ_CERTI_FIELDS"  MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SEQ_CERTI_FIELDS_RELN
--------------------------------------------------------

   CREATE SEQUENCE  "SCHOOL"."SEQ_CERTI_FIELDS_RELN"  MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SEQ_CERTI_FIELD_VALUES
--------------------------------------------------------

   CREATE SEQUENCE  "SCHOOL"."SEQ_CERTI_FIELD_VALUES"  MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SEQ_STD_ACA_PERF_HIST
--------------------------------------------------------

   CREATE SEQUENCE  "SCHOOL"."SEQ_STD_ACA_PERF_HIST"  MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SEQ_STD_ATTND
--------------------------------------------------------

   CREATE SEQUENCE  "SCHOOL"."SEQ_STD_ATTND"  MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SEQ_STD_CURR_STD
--------------------------------------------------------

   CREATE SEQUENCE  "SCHOOL"."SEQ_STD_CURR_STD"  MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SEQ_STD_CURR_STD_PERF
--------------------------------------------------------

   CREATE SEQUENCE  "SCHOOL"."SEQ_STD_CURR_STD_PERF"  MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SEQ_STUDENT
--------------------------------------------------------

   CREATE SEQUENCE  "SCHOOL"."SEQ_STUDENT"  MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Table TBL_ADDRESS
--------------------------------------------------------

  CREATE TABLE "SCHOOL"."TBL_ADDRESS" 
   (	"ID" VARCHAR2(20 BYTE), 
	"VILLAGE" VARCHAR2(20 BYTE), 
	"PO" VARCHAR2(20 BYTE), 
	"PS" VARCHAR2(20 BYTE), 
	"DISTRICT" VARCHAR2(20 BYTE), 
	"STATE" VARCHAR2(20 BYTE), 
	"CITY" VARCHAR2(20 BYTE), 
	"PIN" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SCHOOL" ;
--------------------------------------------------------
--  DDL for Table TBL_ATTND_CLNDR
--------------------------------------------------------

  CREATE TABLE "SCHOOL"."TBL_ATTND_CLNDR" 
   (	"ID" VARCHAR2(10 BYTE), 
	"YEAR" NUMBER(4,0), 
	"MONTH" CHAR(3 BYTE), 
	"CLASS" NUMBER(2,0), 
	"TOT_CLASS" NUMBER(3,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SCHOOL" ;
--------------------------------------------------------
--  DDL for Table TBL_CERTIFICATE
--------------------------------------------------------

  CREATE TABLE "SCHOOL"."TBL_CERTIFICATE" 
   (	"ID" VARCHAR2(20 BYTE), 
	"CERTI_NAME" VARCHAR2(150 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SCHOOL" ;
--------------------------------------------------------
--  DDL for Table TBL_CERTI_FIELDS
--------------------------------------------------------

  CREATE TABLE "SCHOOL"."TBL_CERTI_FIELDS" 
   (	"ID" VARCHAR2(20 BYTE), 
	"FIELD_NAME" VARCHAR2(50 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SCHOOL" ;
--------------------------------------------------------
--  DDL for Table TBL_CERTI_FIELDS_RELN
--------------------------------------------------------

  CREATE TABLE "SCHOOL"."TBL_CERTI_FIELDS_RELN" 
   (	"ID" VARCHAR2(20 BYTE), 
	"CERTIFICATE" VARCHAR2(20 BYTE), 
	"CERTI_FIELDS" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SCHOOL" ;
--------------------------------------------------------
--  DDL for Table TBL_CERTI_FIELD_VALUES
--------------------------------------------------------

  CREATE TABLE "SCHOOL"."TBL_CERTI_FIELD_VALUES" 
   (	"ID" VARCHAR2(20 BYTE), 
	"CERTI_FIELD_RELN" VARCHAR2(20 BYTE), 
	"STUDENT" VARCHAR2(80 BYTE), 
	"FIELD_VALUE" VARCHAR2(100 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SCHOOL" ;
--------------------------------------------------------
--  DDL for Table TBL_CLASS_SUB_RELN
--------------------------------------------------------

  CREATE TABLE "SCHOOL"."TBL_CLASS_SUB_RELN" 
   (	"CLASS" NUMBER(12,0), 
	"SUBJECT" VARCHAR2(20 BYTE), 
	"ID" VARCHAR2(10 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SCHOOL" ;
--------------------------------------------------------
--  DDL for Table TBL_STD_ACA_PERF_HIST
--------------------------------------------------------

  CREATE TABLE "SCHOOL"."TBL_STD_ACA_PERF_HIST" 
   (	"STUDENT" VARCHAR2(80 BYTE), 
	"ID" VARCHAR2(20 BYTE), 
	"SUB_CODE" VARCHAR2(10 BYTE), 
	"SEMESTER" NUMBER(1,0), 
	"MARKS" NUMBER(3,0), 
	"YEAR" NUMBER(4,0), 
	"PROMOTION" CHAR(3 BYTE), 
	"REMARKS" VARCHAR2(200 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SCHOOL" ;
--------------------------------------------------------
--  DDL for Table TBL_STD_ATTND
--------------------------------------------------------

  CREATE TABLE "SCHOOL"."TBL_STD_ATTND" 
   (	"ATT_CAL" VARCHAR2(10 BYTE), 
	"ID" VARCHAR2(20 BYTE), 
	"STUDENT" VARCHAR2(80 BYTE), 
	"ATTENDANCE" NUMBER(3,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SCHOOL" ;
--------------------------------------------------------
--  DDL for Table TBL_STD_CURR_STD
--------------------------------------------------------

  CREATE TABLE "SCHOOL"."TBL_STD_CURR_STD" 
   (	"STUDENT" VARCHAR2(80 BYTE), 
	"ID" VARCHAR2(20 BYTE), 
	"CLASS" NUMBER(2,0), 
	"SEC" CHAR(1 BYTE), 
	"ROLL_NO" NUMBER(3,0), 
	"STREAM" VARCHAR2(20 BYTE), 
	"YEAR" NUMBER(4,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SCHOOL" ;
--------------------------------------------------------
--  DDL for Table TBL_STD_CURR_STD_PERF
--------------------------------------------------------

  CREATE TABLE "SCHOOL"."TBL_STD_CURR_STD_PERF" 
   (	"STUDENT" VARCHAR2(80 BYTE), 
	"ID" VARCHAR2(20 BYTE), 
	"SEMESTER" NUMBER(1,0), 
	"SUB_CODE" VARCHAR2(10 BYTE), 
	"MARKS" NUMBER(3,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SCHOOL" ;
--------------------------------------------------------
--  DDL for Table TBL_STUDENT
--------------------------------------------------------

  CREATE TABLE "SCHOOL"."TBL_STUDENT" 
   (	"ID" VARCHAR2(80 BYTE), 
	"STDNT_NAME" VARCHAR2(100 BYTE), 
	"MOTH_NAME" VARCHAR2(100 BYTE), 
	"CONT_NO" NUMBER(10,0), 
	"DOB" DATE, 
	"BPL" CHAR(1 BYTE), 
	"ID_MARK" VARCHAR2(20 BYTE), 
	"BORAD_NAME" VARCHAR2(100 BYTE), 
	"R_NO" NUMBER(5,0), 
	"MO_MP_HS" NUMBER(5,0), 
	"GRADE_MP_HS" CHAR(1 BYTE), 
	"SL_NO" NUMBER(10,0), 
	"ADM_DATE" DATE, 
	"STD_ROLL_NO" NUMBER(3,0), 
	"GUARD_NAME" VARCHAR2(100 BYTE), 
	"INST_NAME" VARCHAR2(100 BYTE), 
	"MRK_LAST_CLASS" NUMBER(5,0), 
	"LAST_CLASS" NUMBER(2,0), 
	"ADM_CLASS" NUMBER(2,0), 
	"ADM_SEC" CHAR(1 BYTE), 
	"RELIGION" VARCHAR2(20 BYTE), 
	"CASTE" VARCHAR2(20 BYTE), 
	"SEX" CHAR(1 BYTE), 
	"ML_STATUS" VARCHAR2(10 BYTE), 
	"STREEM" VARCHAR2(15 BYTE), 
	"SUBJECT" VARCHAR2(30 BYTE), 
	"FEES_E_P" CHAR(1 BYTE), 
	"FEE_AMT" NUMBER(5,0), 
	"PRF_PHOTO" VARCHAR2(200 BYTE), 
	"PRF_CERTI" VARCHAR2(200 BYTE), 
	"PRF_DOB" VARCHAR2(200 BYTE), 
	"PRF_APP_FORM" VARCHAR2(200 BYTE), 
	"CURRENT_ADDRESS" VARCHAR2(20 BYTE), 
	"PERMANENT_ADDRESS" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SCHOOL" ;
REM INSERTING into SCHOOL.TBL_ADDRESS
SET DEFINE OFF;
REM INSERTING into SCHOOL.TBL_ATTND_CLNDR
SET DEFINE OFF;
REM INSERTING into SCHOOL.TBL_CERTIFICATE
SET DEFINE OFF;
REM INSERTING into SCHOOL.TBL_CERTI_FIELDS
SET DEFINE OFF;
REM INSERTING into SCHOOL.TBL_CERTI_FIELDS_RELN
SET DEFINE OFF;
REM INSERTING into SCHOOL.TBL_CERTI_FIELD_VALUES
SET DEFINE OFF;
REM INSERTING into SCHOOL.TBL_CLASS_SUB_RELN
SET DEFINE OFF;
Insert into SCHOOL.TBL_CLASS_SUB_RELN (CLASS,SUBJECT,ID) values (5,'LANG1','LA1_5');
Insert into SCHOOL.TBL_CLASS_SUB_RELN (CLASS,SUBJECT,ID) values (5,'LANG2','LA2_5');
Insert into SCHOOL.TBL_CLASS_SUB_RELN (CLASS,SUBJECT,ID) values (5,'LANG3','LA3_5');
Insert into SCHOOL.TBL_CLASS_SUB_RELN (CLASS,SUBJECT,ID) values (5,'MATHS','MA_5');
Insert into SCHOOL.TBL_CLASS_SUB_RELN (CLASS,SUBJECT,ID) values (5,'ENV_SCIENCE','ES_5');
Insert into SCHOOL.TBL_CLASS_SUB_RELN (CLASS,SUBJECT,ID) values (5,'HISTORY','HI_5');
Insert into SCHOOL.TBL_CLASS_SUB_RELN (CLASS,SUBJECT,ID) values (5,'GEOGRAPHY','GE_5');
Insert into SCHOOL.TBL_CLASS_SUB_RELN (CLASS,SUBJECT,ID) values (6,'LANG1','LA1_6');
Insert into SCHOOL.TBL_CLASS_SUB_RELN (CLASS,SUBJECT,ID) values (6,'LANG2','LA2_6');
Insert into SCHOOL.TBL_CLASS_SUB_RELN (CLASS,SUBJECT,ID) values (6,'LANG3','LA3_6');
Insert into SCHOOL.TBL_CLASS_SUB_RELN (CLASS,SUBJECT,ID) values (6,'MATHS','MA_6');
Insert into SCHOOL.TBL_CLASS_SUB_RELN (CLASS,SUBJECT,ID) values (6,'ENV_SCIENCE','ES_6');
Insert into SCHOOL.TBL_CLASS_SUB_RELN (CLASS,SUBJECT,ID) values (6,'HISTORY','HI_6');
Insert into SCHOOL.TBL_CLASS_SUB_RELN (CLASS,SUBJECT,ID) values (6,'GEOGRAPHY','GE_6');
Insert into SCHOOL.TBL_CLASS_SUB_RELN (CLASS,SUBJECT,ID) values (7,'LANG1','LA1_7');
Insert into SCHOOL.TBL_CLASS_SUB_RELN (CLASS,SUBJECT,ID) values (7,'LANG2','LA2_7');
Insert into SCHOOL.TBL_CLASS_SUB_RELN (CLASS,SUBJECT,ID) values (7,'LANG3','LA3_7');
Insert into SCHOOL.TBL_CLASS_SUB_RELN (CLASS,SUBJECT,ID) values (7,'MATHS','MA_7');
Insert into SCHOOL.TBL_CLASS_SUB_RELN (CLASS,SUBJECT,ID) values (7,'ENV_SCIENCE','ES_7');
Insert into SCHOOL.TBL_CLASS_SUB_RELN (CLASS,SUBJECT,ID) values (7,'HISTORY','HI_7');
Insert into SCHOOL.TBL_CLASS_SUB_RELN (CLASS,SUBJECT,ID) values (7,'GEOGRAPHY','GE_7');
Insert into SCHOOL.TBL_CLASS_SUB_RELN (CLASS,SUBJECT,ID) values (8,'LANG1','LA1_8');
Insert into SCHOOL.TBL_CLASS_SUB_RELN (CLASS,SUBJECT,ID) values (8,'LANG2','LA2_8');
Insert into SCHOOL.TBL_CLASS_SUB_RELN (CLASS,SUBJECT,ID) values (8,'LANG3','LA3_8');
Insert into SCHOOL.TBL_CLASS_SUB_RELN (CLASS,SUBJECT,ID) values (8,'MATHS','MA_8');
Insert into SCHOOL.TBL_CLASS_SUB_RELN (CLASS,SUBJECT,ID) values (8,'ENV_SCIENCE','ES_8');
Insert into SCHOOL.TBL_CLASS_SUB_RELN (CLASS,SUBJECT,ID) values (8,'HISTORY','HI_8');
Insert into SCHOOL.TBL_CLASS_SUB_RELN (CLASS,SUBJECT,ID) values (8,'GEOGRAPHY','GE_8');
Insert into SCHOOL.TBL_CLASS_SUB_RELN (CLASS,SUBJECT,ID) values (9,'LANG1','LA1_9');
Insert into SCHOOL.TBL_CLASS_SUB_RELN (CLASS,SUBJECT,ID) values (9,'LANG2','LA2_9');
Insert into SCHOOL.TBL_CLASS_SUB_RELN (CLASS,SUBJECT,ID) values (9,'PHY_SC','PHYSC_9');
Insert into SCHOOL.TBL_CLASS_SUB_RELN (CLASS,SUBJECT,ID) values (9,'LIFE_SC','LIFESC_9');
Insert into SCHOOL.TBL_CLASS_SUB_RELN (CLASS,SUBJECT,ID) values (9,'MATHS','MA_9');
Insert into SCHOOL.TBL_CLASS_SUB_RELN (CLASS,SUBJECT,ID) values (9,'HISTORY','HI_9');
Insert into SCHOOL.TBL_CLASS_SUB_RELN (CLASS,SUBJECT,ID) values (9,'GEOGRAPHY','GE_9');
Insert into SCHOOL.TBL_CLASS_SUB_RELN (CLASS,SUBJECT,ID) values (9,'ADDITIONAL','ADD_9');
Insert into SCHOOL.TBL_CLASS_SUB_RELN (CLASS,SUBJECT,ID) values (9,'ENV_SCIENCE','ES_9');
Insert into SCHOOL.TBL_CLASS_SUB_RELN (CLASS,SUBJECT,ID) values (10,'LANG1','LA1_10');
Insert into SCHOOL.TBL_CLASS_SUB_RELN (CLASS,SUBJECT,ID) values (10,'LANG2','LA2_10');
Insert into SCHOOL.TBL_CLASS_SUB_RELN (CLASS,SUBJECT,ID) values (10,'PHY_SC','PHYSC_10');
Insert into SCHOOL.TBL_CLASS_SUB_RELN (CLASS,SUBJECT,ID) values (10,'LIFE_SC','LIFESC_10');
Insert into SCHOOL.TBL_CLASS_SUB_RELN (CLASS,SUBJECT,ID) values (10,'MATHS','MA_10');
Insert into SCHOOL.TBL_CLASS_SUB_RELN (CLASS,SUBJECT,ID) values (10,'HISTORY','HI_10');
Insert into SCHOOL.TBL_CLASS_SUB_RELN (CLASS,SUBJECT,ID) values (10,'GEOGRAPHY','GE_10');
Insert into SCHOOL.TBL_CLASS_SUB_RELN (CLASS,SUBJECT,ID) values (10,'ADDITIONAL','ADD_10');
Insert into SCHOOL.TBL_CLASS_SUB_RELN (CLASS,SUBJECT,ID) values (10,'ENV_SCIENCE','ES_10');
Insert into SCHOOL.TBL_CLASS_SUB_RELN (CLASS,SUBJECT,ID) values (11,'LANG1','LA1_11');
Insert into SCHOOL.TBL_CLASS_SUB_RELN (CLASS,SUBJECT,ID) values (11,'LANG2','LA2_11');
Insert into SCHOOL.TBL_CLASS_SUB_RELN (CLASS,SUBJECT,ID) values (11,'COMP1','C1_11');
Insert into SCHOOL.TBL_CLASS_SUB_RELN (CLASS,SUBJECT,ID) values (11,'COMP2','C2_11');
Insert into SCHOOL.TBL_CLASS_SUB_RELN (CLASS,SUBJECT,ID) values (11,'COMP3','C3_11');
Insert into SCHOOL.TBL_CLASS_SUB_RELN (CLASS,SUBJECT,ID) values (11,'OPTIONAL_STUDY','OP_11');
Insert into SCHOOL.TBL_CLASS_SUB_RELN (CLASS,SUBJECT,ID) values (11,'ENV_SCIENCE','ES_11');
Insert into SCHOOL.TBL_CLASS_SUB_RELN (CLASS,SUBJECT,ID) values (12,'LANG1','LA1_12');
Insert into SCHOOL.TBL_CLASS_SUB_RELN (CLASS,SUBJECT,ID) values (12,'LANG2','LA2_12');
Insert into SCHOOL.TBL_CLASS_SUB_RELN (CLASS,SUBJECT,ID) values (12,'COMP1','C1_12');
Insert into SCHOOL.TBL_CLASS_SUB_RELN (CLASS,SUBJECT,ID) values (12,'COMP2','C2_12');
Insert into SCHOOL.TBL_CLASS_SUB_RELN (CLASS,SUBJECT,ID) values (12,'COMP3','C3_12');
Insert into SCHOOL.TBL_CLASS_SUB_RELN (CLASS,SUBJECT,ID) values (12,'OPTIONAL_STUDY','OP_12');
Insert into SCHOOL.TBL_CLASS_SUB_RELN (CLASS,SUBJECT,ID) values (12,'ENV_SCIENCE','ES_12');
REM INSERTING into SCHOOL.TBL_STD_ACA_PERF_HIST
SET DEFINE OFF;
REM INSERTING into SCHOOL.TBL_STD_ATTND
SET DEFINE OFF;
REM INSERTING into SCHOOL.TBL_STD_CURR_STD
SET DEFINE OFF;
REM INSERTING into SCHOOL.TBL_STD_CURR_STD_PERF
SET DEFINE OFF;
REM INSERTING into SCHOOL.TBL_STUDENT
SET DEFINE OFF;
--------------------------------------------------------
--  DDL for Index CERTIFICATE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SCHOOL"."CERTIFICATE_PK" ON "SCHOOL"."TBL_CERTIFICATE" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SCHOOL" ;
--------------------------------------------------------
--  DDL for Index CERTI_FIELDS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SCHOOL"."CERTI_FIELDS_PK" ON "SCHOOL"."TBL_CERTI_FIELDS" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SCHOOL" ;
--------------------------------------------------------
--  DDL for Index CERTI_FIELDS_RELN_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SCHOOL"."CERTI_FIELDS_RELN_PK" ON "SCHOOL"."TBL_CERTI_FIELDS_RELN" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SCHOOL" ;
--------------------------------------------------------
--  DDL for Index CERTI_FIELD_VALUES_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SCHOOL"."CERTI_FIELD_VALUES_PK" ON "SCHOOL"."TBL_CERTI_FIELD_VALUES" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SCHOOL" ;
--------------------------------------------------------
--  DDL for Index TBL_ADDRESS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SCHOOL"."TBL_ADDRESS_PK" ON "SCHOOL"."TBL_ADDRESS" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SCHOOL" ;
--------------------------------------------------------
--  DDL for Index TBL_ATTND_CLNDR_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SCHOOL"."TBL_ATTND_CLNDR_PK" ON "SCHOOL"."TBL_ATTND_CLNDR" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SCHOOL" ;
--------------------------------------------------------
--  DDL for Index TBL_CLASS_SUB_RELN_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SCHOOL"."TBL_CLASS_SUB_RELN_PK" ON "SCHOOL"."TBL_CLASS_SUB_RELN" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SCHOOL" ;
--------------------------------------------------------
--  DDL for Index TBL_STD_ACA_PERF_HIST_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SCHOOL"."TBL_STD_ACA_PERF_HIST_PK" ON "SCHOOL"."TBL_STD_ACA_PERF_HIST" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SCHOOL" ;
--------------------------------------------------------
--  DDL for Index TBL_STD_ATTND_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SCHOOL"."TBL_STD_ATTND_PK" ON "SCHOOL"."TBL_STD_ATTND" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SCHOOL" ;
--------------------------------------------------------
--  DDL for Index TBL_STD_CURR_STD_PERF_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SCHOOL"."TBL_STD_CURR_STD_PERF_PK" ON "SCHOOL"."TBL_STD_CURR_STD_PERF" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SCHOOL" ;
--------------------------------------------------------
--  DDL for Index TBL_STD_CURR_STD_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SCHOOL"."TBL_STD_CURR_STD_PK" ON "SCHOOL"."TBL_STD_CURR_STD" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SCHOOL" ;
--------------------------------------------------------
--  DDL for Index TBL_STUDENT_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SCHOOL"."TBL_STUDENT_PK" ON "SCHOOL"."TBL_STUDENT" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SCHOOL" ;
--------------------------------------------------------
--  Constraints for Table TBL_ADDRESS
--------------------------------------------------------

  ALTER TABLE "SCHOOL"."TBL_ADDRESS" ADD CONSTRAINT "TBL_ADDRESS_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SCHOOL"  ENABLE;
  ALTER TABLE "SCHOOL"."TBL_ADDRESS" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table TBL_ATTND_CLNDR
--------------------------------------------------------

  ALTER TABLE "SCHOOL"."TBL_ATTND_CLNDR" ADD CONSTRAINT "TBL_ATTND_CLNDR_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SCHOOL"  ENABLE;
  ALTER TABLE "SCHOOL"."TBL_ATTND_CLNDR" MODIFY ("CLASS" NOT NULL ENABLE);
  ALTER TABLE "SCHOOL"."TBL_ATTND_CLNDR" MODIFY ("MONTH" NOT NULL ENABLE);
  ALTER TABLE "SCHOOL"."TBL_ATTND_CLNDR" MODIFY ("YEAR" NOT NULL ENABLE);
  ALTER TABLE "SCHOOL"."TBL_ATTND_CLNDR" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table TBL_CERTIFICATE
--------------------------------------------------------

  ALTER TABLE "SCHOOL"."TBL_CERTIFICATE" MODIFY ("CERTI_NAME" NOT NULL ENABLE);
  ALTER TABLE "SCHOOL"."TBL_CERTIFICATE" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "SCHOOL"."TBL_CERTIFICATE" ADD CONSTRAINT "CERTIFICATE_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SCHOOL"  ENABLE;
--------------------------------------------------------
--  Constraints for Table TBL_CERTI_FIELDS
--------------------------------------------------------

  ALTER TABLE "SCHOOL"."TBL_CERTI_FIELDS" MODIFY ("FIELD_NAME" NOT NULL ENABLE);
  ALTER TABLE "SCHOOL"."TBL_CERTI_FIELDS" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "SCHOOL"."TBL_CERTI_FIELDS" ADD CONSTRAINT "CERTI_FIELDS_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SCHOOL"  ENABLE;
--------------------------------------------------------
--  Constraints for Table TBL_CERTI_FIELDS_RELN
--------------------------------------------------------

  ALTER TABLE "SCHOOL"."TBL_CERTI_FIELDS_RELN" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "SCHOOL"."TBL_CERTI_FIELDS_RELN" ADD CONSTRAINT "CERTI_FIELDS_RELN_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SCHOOL"  ENABLE;
--------------------------------------------------------
--  Constraints for Table TBL_CERTI_FIELD_VALUES
--------------------------------------------------------

  ALTER TABLE "SCHOOL"."TBL_CERTI_FIELD_VALUES" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "SCHOOL"."TBL_CERTI_FIELD_VALUES" ADD CONSTRAINT "CERTI_FIELD_VALUES_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SCHOOL"  ENABLE;
--------------------------------------------------------
--  Constraints for Table TBL_CLASS_SUB_RELN
--------------------------------------------------------

  ALTER TABLE "SCHOOL"."TBL_CLASS_SUB_RELN" ADD CONSTRAINT "TBL_CLASS_SUB_RELN_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SCHOOL"  ENABLE;
  ALTER TABLE "SCHOOL"."TBL_CLASS_SUB_RELN" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "SCHOOL"."TBL_CLASS_SUB_RELN" MODIFY ("SUBJECT" NOT NULL ENABLE);
  ALTER TABLE "SCHOOL"."TBL_CLASS_SUB_RELN" MODIFY ("CLASS" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table TBL_STD_ACA_PERF_HIST
--------------------------------------------------------

  ALTER TABLE "SCHOOL"."TBL_STD_ACA_PERF_HIST" ADD CONSTRAINT "TBL_STD_ACA_PERF_HIST_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SCHOOL"  ENABLE;
  ALTER TABLE "SCHOOL"."TBL_STD_ACA_PERF_HIST" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "SCHOOL"."TBL_STD_ACA_PERF_HIST" MODIFY ("REMARKS" NOT NULL ENABLE);
  ALTER TABLE "SCHOOL"."TBL_STD_ACA_PERF_HIST" MODIFY ("PROMOTION" NOT NULL ENABLE);
  ALTER TABLE "SCHOOL"."TBL_STD_ACA_PERF_HIST" MODIFY ("YEAR" NOT NULL ENABLE);
  ALTER TABLE "SCHOOL"."TBL_STD_ACA_PERF_HIST" MODIFY ("MARKS" NOT NULL ENABLE);
  ALTER TABLE "SCHOOL"."TBL_STD_ACA_PERF_HIST" MODIFY ("SEMESTER" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table TBL_STD_ATTND
--------------------------------------------------------

  ALTER TABLE "SCHOOL"."TBL_STD_ATTND" ADD CONSTRAINT "TBL_STD_ATTND_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SCHOOL"  ENABLE;
  ALTER TABLE "SCHOOL"."TBL_STD_ATTND" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table TBL_STD_CURR_STD
--------------------------------------------------------

  ALTER TABLE "SCHOOL"."TBL_STD_CURR_STD" ADD CONSTRAINT "TBL_STD_CURR_STD_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SCHOOL"  ENABLE;
  ALTER TABLE "SCHOOL"."TBL_STD_CURR_STD" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "SCHOOL"."TBL_STD_CURR_STD" MODIFY ("YEAR" NOT NULL ENABLE);
  ALTER TABLE "SCHOOL"."TBL_STD_CURR_STD" MODIFY ("ROLL_NO" NOT NULL ENABLE);
  ALTER TABLE "SCHOOL"."TBL_STD_CURR_STD" MODIFY ("SEC" NOT NULL ENABLE);
  ALTER TABLE "SCHOOL"."TBL_STD_CURR_STD" MODIFY ("CLASS" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table TBL_STD_CURR_STD_PERF
--------------------------------------------------------

  ALTER TABLE "SCHOOL"."TBL_STD_CURR_STD_PERF" ADD CONSTRAINT "TBL_STD_CURR_STD_PERF_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SCHOOL"  ENABLE;
  ALTER TABLE "SCHOOL"."TBL_STD_CURR_STD_PERF" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "SCHOOL"."TBL_STD_CURR_STD_PERF" MODIFY ("MARKS" NOT NULL ENABLE);
  ALTER TABLE "SCHOOL"."TBL_STD_CURR_STD_PERF" MODIFY ("SUB_CODE" NOT NULL ENABLE);
  ALTER TABLE "SCHOOL"."TBL_STD_CURR_STD_PERF" MODIFY ("SEMESTER" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table TBL_STUDENT
--------------------------------------------------------

  ALTER TABLE "SCHOOL"."TBL_STUDENT" ADD CONSTRAINT "TBL_STUDENT_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SCHOOL"  ENABLE;
  ALTER TABLE "SCHOOL"."TBL_STUDENT" MODIFY ("BPL" NOT NULL ENABLE);
  ALTER TABLE "SCHOOL"."TBL_STUDENT" MODIFY ("PRF_DOB" NOT NULL ENABLE);
  ALTER TABLE "SCHOOL"."TBL_STUDENT" MODIFY ("PRF_CERTI" NOT NULL ENABLE);
  ALTER TABLE "SCHOOL"."TBL_STUDENT" MODIFY ("PRF_PHOTO" NOT NULL ENABLE);
  ALTER TABLE "SCHOOL"."TBL_STUDENT" MODIFY ("FEE_AMT" NOT NULL ENABLE);
  ALTER TABLE "SCHOOL"."TBL_STUDENT" MODIFY ("FEES_E_P" NOT NULL ENABLE);
  ALTER TABLE "SCHOOL"."TBL_STUDENT" MODIFY ("ML_STATUS" NOT NULL ENABLE);
  ALTER TABLE "SCHOOL"."TBL_STUDENT" MODIFY ("SEX" NOT NULL ENABLE);
  ALTER TABLE "SCHOOL"."TBL_STUDENT" MODIFY ("CASTE" NOT NULL ENABLE);
  ALTER TABLE "SCHOOL"."TBL_STUDENT" MODIFY ("RELIGION" NOT NULL ENABLE);
  ALTER TABLE "SCHOOL"."TBL_STUDENT" MODIFY ("ADM_SEC" NOT NULL ENABLE);
  ALTER TABLE "SCHOOL"."TBL_STUDENT" MODIFY ("ADM_CLASS" NOT NULL ENABLE);
  ALTER TABLE "SCHOOL"."TBL_STUDENT" MODIFY ("GUARD_NAME" NOT NULL ENABLE);
  ALTER TABLE "SCHOOL"."TBL_STUDENT" MODIFY ("STD_ROLL_NO" NOT NULL ENABLE);
  ALTER TABLE "SCHOOL"."TBL_STUDENT" MODIFY ("ADM_DATE" NOT NULL ENABLE);
  ALTER TABLE "SCHOOL"."TBL_STUDENT" MODIFY ("SL_NO" NOT NULL ENABLE);
  ALTER TABLE "SCHOOL"."TBL_STUDENT" MODIFY ("DOB" NOT NULL ENABLE);
  ALTER TABLE "SCHOOL"."TBL_STUDENT" MODIFY ("CONT_NO" NOT NULL ENABLE);
  ALTER TABLE "SCHOOL"."TBL_STUDENT" MODIFY ("STDNT_NAME" NOT NULL ENABLE);
  ALTER TABLE "SCHOOL"."TBL_STUDENT" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table TBL_CERTI_FIELDS_RELN
--------------------------------------------------------

  ALTER TABLE "SCHOOL"."TBL_CERTI_FIELDS_RELN" ADD CONSTRAINT "CERTI_FIELDS_RELN_CERTIFI_FK1" FOREIGN KEY ("CERTIFICATE")
	  REFERENCES "SCHOOL"."TBL_CERTIFICATE" ("ID") ON DELETE CASCADE ENABLE;
  ALTER TABLE "SCHOOL"."TBL_CERTI_FIELDS_RELN" ADD CONSTRAINT "CERTI_FIELDS_RELN_CERTI_F_FK1" FOREIGN KEY ("CERTI_FIELDS")
	  REFERENCES "SCHOOL"."TBL_CERTI_FIELDS" ("ID") ON DELETE CASCADE ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table TBL_CERTI_FIELD_VALUES
--------------------------------------------------------

  ALTER TABLE "SCHOOL"."TBL_CERTI_FIELD_VALUES" ADD CONSTRAINT "CERTI_FIELD_VALUES_CERTI__FK1" FOREIGN KEY ("CERTI_FIELD_RELN")
	  REFERENCES "SCHOOL"."TBL_CERTI_FIELDS_RELN" ("ID") ON DELETE CASCADE ENABLE;
  ALTER TABLE "SCHOOL"."TBL_CERTI_FIELD_VALUES" ADD CONSTRAINT "CERTI_FIELD_VALUES_TBL_ST_FK1" FOREIGN KEY ("STUDENT")
	  REFERENCES "SCHOOL"."TBL_STUDENT" ("ID") ON DELETE CASCADE ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table TBL_STD_ACA_PERF_HIST
--------------------------------------------------------

  ALTER TABLE "SCHOOL"."TBL_STD_ACA_PERF_HIST" ADD CONSTRAINT "TBL_STD_ACA_PERF_HIST_TBL_FK1" FOREIGN KEY ("STUDENT")
	  REFERENCES "SCHOOL"."TBL_STUDENT" ("ID") ON DELETE CASCADE ENABLE;
  ALTER TABLE "SCHOOL"."TBL_STD_ACA_PERF_HIST" ADD CONSTRAINT "TBL_STD_ACA_PERF_HIST_TBL_FK2" FOREIGN KEY ("SUB_CODE")
	  REFERENCES "SCHOOL"."TBL_CLASS_SUB_RELN" ("ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table TBL_STD_ATTND
--------------------------------------------------------

  ALTER TABLE "SCHOOL"."TBL_STD_ATTND" ADD CONSTRAINT "TBL_STD_ATTND_TBL_ATTND_C_FK1" FOREIGN KEY ("ATT_CAL")
	  REFERENCES "SCHOOL"."TBL_ATTND_CLNDR" ("ID") ON DELETE CASCADE ENABLE;
  ALTER TABLE "SCHOOL"."TBL_STD_ATTND" ADD CONSTRAINT "TBL_STD_ATTND_TBL_STUDENT_FK1" FOREIGN KEY ("STUDENT")
	  REFERENCES "SCHOOL"."TBL_STUDENT" ("ID") ON DELETE CASCADE ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table TBL_STD_CURR_STD
--------------------------------------------------------

  ALTER TABLE "SCHOOL"."TBL_STD_CURR_STD" ADD CONSTRAINT "TBL_STD_CURR_STD_TBL_STUD_FK1" FOREIGN KEY ("STUDENT")
	  REFERENCES "SCHOOL"."TBL_STUDENT" ("ID") ON DELETE CASCADE ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table TBL_STD_CURR_STD_PERF
--------------------------------------------------------

  ALTER TABLE "SCHOOL"."TBL_STD_CURR_STD_PERF" ADD CONSTRAINT "TBL_STD_CURR_STD_PERF_TBL_FK1" FOREIGN KEY ("STUDENT")
	  REFERENCES "SCHOOL"."TBL_STUDENT" ("ID") ON DELETE CASCADE ENABLE;
  ALTER TABLE "SCHOOL"."TBL_STD_CURR_STD_PERF" ADD CONSTRAINT "TBL_STD_CURR_STD_PERF_TBL_FK2" FOREIGN KEY ("SUB_CODE")
	  REFERENCES "SCHOOL"."TBL_CLASS_SUB_RELN" ("ID") ON DELETE CASCADE ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table TBL_STUDENT
--------------------------------------------------------

  ALTER TABLE "SCHOOL"."TBL_STUDENT" ADD CONSTRAINT "TBL_STUDENT_FK1" FOREIGN KEY ("CURRENT_ADDRESS")
	  REFERENCES "SCHOOL"."TBL_ADDRESS" ("ID") ENABLE;
  ALTER TABLE "SCHOOL"."TBL_STUDENT" ADD CONSTRAINT "TBL_STUDENT_FK2" FOREIGN KEY ("PERMANENT_ADDRESS")
	  REFERENCES "SCHOOL"."TBL_ADDRESS" ("ID") ENABLE;
--------------------------------------------------------
--  DDL for Procedure GEN_ROLL_NO
--------------------------------------------------------
set define off;

  CREATE OR REPLACE PROCEDURE "SCHOOL"."GEN_ROLL_NO" 
(v_section in tbl_student.adm_sec%type,
v_class in tbl_student.adm_class%type,
v_roll_no out tbl_student.std_roll_no%type)
is
v_no tbl_student.std_roll_no%type;
begin
select max(std_roll_no) into v_no from tbl_student where adm_class=v_class and adm_sec=v_section;
v_roll_no:=v_no+1;
exception
when no_data_found then
v_roll_no:=1;
end;

/
