--------------------------------------------------------
--  File created - Monday-November-23-2015   
--------------------------------------------------------
DROP TABLE "SCHOOL"."TBL_ADDRESS" cascade constraints;
DROP TABLE "SCHOOL"."TBL_ATTND_CLNDR" cascade constraints;
DROP TABLE "SCHOOL"."TBL_CERTIFICATE" cascade constraints;
DROP TABLE "SCHOOL"."TBL_CERTI_FIELDS" cascade constraints;
DROP TABLE "SCHOOL"."TBL_CERTI_FIELDS_RELN" cascade constraints;
DROP TABLE "SCHOOL"."TBL_CERTI_FIELD_VALUES" cascade constraints;
DROP TABLE "SCHOOL"."TBL_CLASS_SUB_RELN" cascade constraints;
DROP TABLE "SCHOOL"."TBL_STD_ACA_PERF_HIST" cascade constraints;
DROP TABLE "SCHOOL"."TBL_STD_ATTND" cascade constraints;
DROP TABLE "SCHOOL"."TBL_STD_CURR_STD" cascade constraints;
DROP TABLE "SCHOOL"."TBL_STD_CURR_STD_PERF" cascade constraints;
DROP TABLE "SCHOOL"."TBL_STUDENT" cascade constraints;
DROP TABLE "SCHOOL"."BIN$9Dkl+SK0S3KoijJezd5EZg==$0" cascade constraints;
DROP SYNONYM "PUBLIC"."DUAL";
DROP SEQUENCE "SCHOOL"."SEQ_ADDRESS";
DROP SEQUENCE "SCHOOL"."SEQ_ATTND_CLNDR";
DROP SEQUENCE "SCHOOL"."SEQ_CERTIFICATE";
DROP SEQUENCE "SCHOOL"."SEQ_CERTI_FIELDS";
DROP SEQUENCE "SCHOOL"."SEQ_CERTI_FIELDS_RELN";
DROP SEQUENCE "SCHOOL"."SEQ_CERTI_FIELD_VALUES";
DROP SEQUENCE "SCHOOL"."SEQ_STD_ACA_PERF_HIST";
DROP SEQUENCE "SCHOOL"."SEQ_STD_ATTND";
DROP SEQUENCE "SCHOOL"."SEQ_STD_CURR_STD";
DROP SEQUENCE "SCHOOL"."SEQ_STD_CURR_STD_PERF";
DROP SEQUENCE "SCHOOL"."SEQ_STUDENT";
DROP FUNCTION "SCHOOL"."FUN_GEN_ROLL_NO";
DROP PROCEDURE "SCHOOL"."GEN_ROLL_NO";
--------------------------------------------------------
--  DDL for Sequence SEQ_ADDRESS
--------------------------------------------------------

   CREATE SEQUENCE  "SCHOOL"."SEQ_ADDRESS"  MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 41 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SEQ_ATTND_CLNDR
--------------------------------------------------------

   CREATE SEQUENCE  "SCHOOL"."SEQ_ATTND_CLNDR"  MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SEQ_CERTIFICATE
--------------------------------------------------------

   CREATE SEQUENCE  "SCHOOL"."SEQ_CERTIFICATE"  MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SEQ_CERTI_FIELDS
--------------------------------------------------------

   CREATE SEQUENCE  "SCHOOL"."SEQ_CERTI_FIELDS"  MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SEQ_CERTI_FIELDS_RELN
--------------------------------------------------------

   CREATE SEQUENCE  "SCHOOL"."SEQ_CERTI_FIELDS_RELN"  MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SEQ_CERTI_FIELD_VALUES
--------------------------------------------------------

   CREATE SEQUENCE  "SCHOOL"."SEQ_CERTI_FIELD_VALUES"  MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SEQ_STD_ACA_PERF_HIST
--------------------------------------------------------

   CREATE SEQUENCE  "SCHOOL"."SEQ_STD_ACA_PERF_HIST"  MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SEQ_STD_ATTND
--------------------------------------------------------

   CREATE SEQUENCE  "SCHOOL"."SEQ_STD_ATTND"  MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SEQ_STD_CURR_STD
--------------------------------------------------------

   CREATE SEQUENCE  "SCHOOL"."SEQ_STD_CURR_STD"  MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 21 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SEQ_STD_CURR_STD_PERF
--------------------------------------------------------

   CREATE SEQUENCE  "SCHOOL"."SEQ_STD_CURR_STD_PERF"  MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SEQ_STUDENT
--------------------------------------------------------

   CREATE SEQUENCE  "SCHOOL"."SEQ_STUDENT"  MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 41 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Table TBL_ADDRESS
--------------------------------------------------------

  CREATE TABLE "SCHOOL"."TBL_ADDRESS" 
   (	"ID" NUMBER(38,0), 
	"VILLAGE" VARCHAR2(20 BYTE), 
	"PO" VARCHAR2(20 BYTE), 
	"PS" VARCHAR2(20 BYTE), 
	"DISTRICT" VARCHAR2(20 BYTE), 
	"STATE" VARCHAR2(20 BYTE), 
	"CITY" VARCHAR2(20 BYTE), 
	"PIN" VARCHAR2(20 BYTE), 
	"LINE1" VARCHAR2(255 BYTE), 
	"LINE2" VARCHAR2(255 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SCHOOL" ;
--------------------------------------------------------
--  DDL for Table TBL_ATTND_CLNDR
--------------------------------------------------------

  CREATE TABLE "SCHOOL"."TBL_ATTND_CLNDR" 
   (	"ID" NUMBER(38,0), 
	"YEAR" NUMBER(4,0), 
	"MONTH" CHAR(3 BYTE), 
	"CLASS" NUMBER(2,0), 
	"TOT_CLASS" NUMBER(3,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SCHOOL" ;
--------------------------------------------------------
--  DDL for Table TBL_CERTIFICATE
--------------------------------------------------------

  CREATE TABLE "SCHOOL"."TBL_CERTIFICATE" 
   (	"ID" NUMBER(38,0), 
	"CERTI_NAME" VARCHAR2(150 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SCHOOL" ;
--------------------------------------------------------
--  DDL for Table TBL_CERTI_FIELDS
--------------------------------------------------------

  CREATE TABLE "SCHOOL"."TBL_CERTI_FIELDS" 
   (	"ID" NUMBER(38,0), 
	"FIELD_NAME" VARCHAR2(50 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SCHOOL" ;
--------------------------------------------------------
--  DDL for Table TBL_CERTI_FIELDS_RELN
--------------------------------------------------------

  CREATE TABLE "SCHOOL"."TBL_CERTI_FIELDS_RELN" 
   (	"ID" NUMBER(38,0), 
	"CERTIFICATE" NUMBER(38,0), 
	"CERTI_FIELDS" NUMBER(38,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SCHOOL" ;
--------------------------------------------------------
--  DDL for Table TBL_CERTI_FIELD_VALUES
--------------------------------------------------------

  CREATE TABLE "SCHOOL"."TBL_CERTI_FIELD_VALUES" 
   (	"ID" NUMBER(38,0), 
	"CERTI_FIELD_RELN" NUMBER(38,0), 
	"STUDENT" NUMBER(38,0), 
	"FIELD_VALUE" VARCHAR2(100 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SCHOOL" ;
--------------------------------------------------------
--  DDL for Table TBL_CLASS_SUB_RELN
--------------------------------------------------------

  CREATE TABLE "SCHOOL"."TBL_CLASS_SUB_RELN" 
   (	"CLASS" NUMBER(12,0), 
	"SUBJECT" VARCHAR2(20 BYTE), 
	"ID" NUMBER(38,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SCHOOL" ;
--------------------------------------------------------
--  DDL for Table TBL_STD_ACA_PERF_HIST
--------------------------------------------------------

  CREATE TABLE "SCHOOL"."TBL_STD_ACA_PERF_HIST" 
   (	"STUDENT" NUMBER(38,0), 
	"ID" NUMBER(38,0), 
	"SUB_CODE" NUMBER(38,0), 
	"SEMESTER" NUMBER(1,0), 
	"MARKS" NUMBER(3,0), 
	"YEAR" NUMBER(4,0), 
	"PROMOTION" CHAR(3 BYTE), 
	"REMARKS" VARCHAR2(200 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SCHOOL" ;
--------------------------------------------------------
--  DDL for Table TBL_STD_ATTND
--------------------------------------------------------

  CREATE TABLE "SCHOOL"."TBL_STD_ATTND" 
   (	"ATT_CAL" NUMBER(38,0), 
	"ID" NUMBER(38,0), 
	"STUDENT" NUMBER(38,0), 
	"ATTENDANCE" NUMBER(3,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SCHOOL" ;
--------------------------------------------------------
--  DDL for Table TBL_STD_CURR_STD
--------------------------------------------------------

  CREATE TABLE "SCHOOL"."TBL_STD_CURR_STD" 
   (	"STUDENT" NUMBER(38,0), 
	"ID" NUMBER(38,0), 
	"CLASS" NUMBER(2,0), 
	"SEC" CHAR(1 BYTE), 
	"ROLL_NO" NUMBER(3,0), 
	"STREAM" VARCHAR2(20 BYTE), 
	"YEAR" NUMBER(4,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SCHOOL" ;
--------------------------------------------------------
--  DDL for Table TBL_STD_CURR_STD_PERF
--------------------------------------------------------

  CREATE TABLE "SCHOOL"."TBL_STD_CURR_STD_PERF" 
   (	"STUDENT" NUMBER(38,0), 
	"ID" NUMBER(38,0), 
	"SEMESTER" NUMBER(1,0), 
	"SUB_CODE" NUMBER(38,0), 
	"MARKS" NUMBER(3,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SCHOOL" ;
--------------------------------------------------------
--  DDL for Table TBL_STUDENT
--------------------------------------------------------

  CREATE TABLE "SCHOOL"."TBL_STUDENT" 
   (	"ID" NUMBER(38,0), 
	"STDNT_NAME" VARCHAR2(100 BYTE), 
	"MOTH_NAME" VARCHAR2(100 BYTE), 
	"CONT_NO" NUMBER(10,0), 
	"DOB" DATE, 
	"BPL" VARCHAR2(4 BYTE), 
	"ID_MARK" VARCHAR2(20 BYTE), 
	"BORAD_NAME" VARCHAR2(100 BYTE), 
	"R_NO" NUMBER(5,0), 
	"MO_MP_HS" NUMBER(5,0), 
	"GRADE_MP_HS" CHAR(1 BYTE), 
	"SL_NO" NUMBER(10,0), 
	"ADM_DATE" DATE, 
	"STD_ROLL_NO" NUMBER(3,0), 
	"GUARD_NAME" VARCHAR2(100 BYTE), 
	"INST_NAME" VARCHAR2(100 BYTE), 
	"MRK_LAST_CLASS" NUMBER(5,0), 
	"LAST_CLASS" NUMBER(2,0), 
	"ADM_CLASS" NUMBER(2,0), 
	"ADM_SEC" CHAR(1 BYTE), 
	"RELIGION" VARCHAR2(20 BYTE), 
	"CASTE" VARCHAR2(20 BYTE), 
	"SEX" VARCHAR2(20 BYTE), 
	"ML_STATUS" VARCHAR2(10 BYTE), 
	"STREAM" VARCHAR2(15 BYTE), 
	"SUBJECT" VARCHAR2(30 BYTE), 
	"FEES_E_P" CHAR(1 BYTE), 
	"FEE_AMT" NUMBER(5,0), 
	"PRF_PHOTO" VARCHAR2(200 BYTE), 
	"PRF_CERTI" VARCHAR2(200 BYTE), 
	"PRF_DOB" VARCHAR2(200 BYTE), 
	"PRF_APP_FORM" VARCHAR2(200 BYTE), 
	"CURRENT_ADDRESS" NUMBER(38,0), 
	"PERMANENT_ADDRESS" NUMBER(38,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SCHOOL" ;
REM INSERTING into SCHOOL.TBL_ADDRESS
SET DEFINE OFF;
Insert into SCHOOL.TBL_ADDRESS (ID,VILLAGE,PO,PS,DISTRICT,STATE,CITY,PIN,LINE1,LINE2) values (2,'V','PO','Ps','D','West Bengal','C','700010','L1','L2');
Insert into SCHOOL.TBL_ADDRESS (ID,VILLAGE,PO,PS,DISTRICT,STATE,CITY,PIN,LINE1,LINE2) values (3,'V','PO','Ps','D','West Bengal','C','0','L1','L2');
Insert into SCHOOL.TBL_ADDRESS (ID,VILLAGE,PO,PS,DISTRICT,STATE,CITY,PIN,LINE1,LINE2) values (4,'V','PO','Ps','D','West Bengal','C','700010','L1','L2');
Insert into SCHOOL.TBL_ADDRESS (ID,VILLAGE,PO,PS,DISTRICT,STATE,CITY,PIN,LINE1,LINE2) values (5,'V','PO','Ps','D','West Bengal','C','0','L1','L2');
Insert into SCHOOL.TBL_ADDRESS (ID,VILLAGE,PO,PS,DISTRICT,STATE,CITY,PIN,LINE1,LINE2) values (6,'V','PO','Ps','D','West Bengal','C','700010','L1','L2');
Insert into SCHOOL.TBL_ADDRESS (ID,VILLAGE,PO,PS,DISTRICT,STATE,CITY,PIN,LINE1,LINE2) values (7,'V','PO','Ps','D','West Bengal','C','0','L1','L2');
Insert into SCHOOL.TBL_ADDRESS (ID,VILLAGE,PO,PS,DISTRICT,STATE,CITY,PIN,LINE1,LINE2) values (8,'V','PO','Ps','D','West Bengal','C','700010','L1','L2');
Insert into SCHOOL.TBL_ADDRESS (ID,VILLAGE,PO,PS,DISTRICT,STATE,CITY,PIN,LINE1,LINE2) values (9,'V','PO','Ps','D','West Bengal','C','0','L1','L2');
Insert into SCHOOL.TBL_ADDRESS (ID,VILLAGE,PO,PS,DISTRICT,STATE,CITY,PIN,LINE1,LINE2) values (10,'V','PO','Ps','D','West Bengal','C','700010','L1','L2');
Insert into SCHOOL.TBL_ADDRESS (ID,VILLAGE,PO,PS,DISTRICT,STATE,CITY,PIN,LINE1,LINE2) values (11,'V','PO','Ps','D','West Bengal','C','0','L1','L2');
Insert into SCHOOL.TBL_ADDRESS (ID,VILLAGE,PO,PS,DISTRICT,STATE,CITY,PIN,LINE1,LINE2) values (12,'V','PO','Ps','D','West Bengal','C','700010','L1','L2');
Insert into SCHOOL.TBL_ADDRESS (ID,VILLAGE,PO,PS,DISTRICT,STATE,CITY,PIN,LINE1,LINE2) values (13,'V','PO','Ps','D','West Bengal','C','0','L1','L2');
Insert into SCHOOL.TBL_ADDRESS (ID,VILLAGE,PO,PS,DISTRICT,STATE,CITY,PIN,LINE1,LINE2) values (14,'V','PO','Ps','D','West Bengal','C','700010','L1','L2');
Insert into SCHOOL.TBL_ADDRESS (ID,VILLAGE,PO,PS,DISTRICT,STATE,CITY,PIN,LINE1,LINE2) values (15,'V','PO','Ps','D','West Bengal','C','0','L1','L2');
Insert into SCHOOL.TBL_ADDRESS (ID,VILLAGE,PO,PS,DISTRICT,STATE,CITY,PIN,LINE1,LINE2) values (16,'V','PO','Ps','D','West Bengal','C','700010','L1','L2');
Insert into SCHOOL.TBL_ADDRESS (ID,VILLAGE,PO,PS,DISTRICT,STATE,CITY,PIN,LINE1,LINE2) values (17,'V','PO','Ps','D','West Bengal','C','0','L1','L2');
Insert into SCHOOL.TBL_ADDRESS (ID,VILLAGE,PO,PS,DISTRICT,STATE,CITY,PIN,LINE1,LINE2) values (18,'V','PO','Ps','D','West Bengal','C','700010','L1','L2');
Insert into SCHOOL.TBL_ADDRESS (ID,VILLAGE,PO,PS,DISTRICT,STATE,CITY,PIN,LINE1,LINE2) values (19,'V','PO','Ps','D','West Bengal','C','0','L1','L2');
Insert into SCHOOL.TBL_ADDRESS (ID,VILLAGE,PO,PS,DISTRICT,STATE,CITY,PIN,LINE1,LINE2) values (20,'V','PO','Ps','D','West Bengal','C','700010','L1','L2');
Insert into SCHOOL.TBL_ADDRESS (ID,VILLAGE,PO,PS,DISTRICT,STATE,CITY,PIN,LINE1,LINE2) values (21,'V','PO','Ps','D','West Bengal','C','0','L1','L2');
REM INSERTING into SCHOOL.TBL_ATTND_CLNDR
SET DEFINE OFF;
REM INSERTING into SCHOOL.TBL_CERTIFICATE
SET DEFINE OFF;
REM INSERTING into SCHOOL.TBL_CERTI_FIELDS
SET DEFINE OFF;
REM INSERTING into SCHOOL.TBL_CERTI_FIELDS_RELN
SET DEFINE OFF;
REM INSERTING into SCHOOL.TBL_CERTI_FIELD_VALUES
SET DEFINE OFF;
REM INSERTING into SCHOOL.TBL_CLASS_SUB_RELN
SET DEFINE OFF;
Insert into SCHOOL.TBL_CLASS_SUB_RELN (CLASS,SUBJECT,ID) values (5,'LANG1',51);
Insert into SCHOOL.TBL_CLASS_SUB_RELN (CLASS,SUBJECT,ID) values (5,'LANG2',52);
Insert into SCHOOL.TBL_CLASS_SUB_RELN (CLASS,SUBJECT,ID) values (5,'LANG3',53);
Insert into SCHOOL.TBL_CLASS_SUB_RELN (CLASS,SUBJECT,ID) values (5,'MATHS',54);
Insert into SCHOOL.TBL_CLASS_SUB_RELN (CLASS,SUBJECT,ID) values (5,'ENV_SCIENCE',55);
Insert into SCHOOL.TBL_CLASS_SUB_RELN (CLASS,SUBJECT,ID) values (5,'HISTORY',56);
Insert into SCHOOL.TBL_CLASS_SUB_RELN (CLASS,SUBJECT,ID) values (5,'GEOGRAPHY',57);
Insert into SCHOOL.TBL_CLASS_SUB_RELN (CLASS,SUBJECT,ID) values (6,'LANG1',61);
Insert into SCHOOL.TBL_CLASS_SUB_RELN (CLASS,SUBJECT,ID) values (6,'LANG2',62);
Insert into SCHOOL.TBL_CLASS_SUB_RELN (CLASS,SUBJECT,ID) values (6,'LANG3',63);
Insert into SCHOOL.TBL_CLASS_SUB_RELN (CLASS,SUBJECT,ID) values (6,'MATHS',64);
Insert into SCHOOL.TBL_CLASS_SUB_RELN (CLASS,SUBJECT,ID) values (6,'ENV_SCIENCE',65);
Insert into SCHOOL.TBL_CLASS_SUB_RELN (CLASS,SUBJECT,ID) values (6,'HISTORY',66);
Insert into SCHOOL.TBL_CLASS_SUB_RELN (CLASS,SUBJECT,ID) values (6,'GEOGRAPHY',67);
Insert into SCHOOL.TBL_CLASS_SUB_RELN (CLASS,SUBJECT,ID) values (7,'LANG1',71);
Insert into SCHOOL.TBL_CLASS_SUB_RELN (CLASS,SUBJECT,ID) values (7,'LANG2',72);
Insert into SCHOOL.TBL_CLASS_SUB_RELN (CLASS,SUBJECT,ID) values (7,'LANG3',73);
Insert into SCHOOL.TBL_CLASS_SUB_RELN (CLASS,SUBJECT,ID) values (7,'MATHS',74);
Insert into SCHOOL.TBL_CLASS_SUB_RELN (CLASS,SUBJECT,ID) values (7,'ENV_SCIENCE',75);
Insert into SCHOOL.TBL_CLASS_SUB_RELN (CLASS,SUBJECT,ID) values (7,'HISTORY',76);
Insert into SCHOOL.TBL_CLASS_SUB_RELN (CLASS,SUBJECT,ID) values (7,'GEOGRAPHY',77);
Insert into SCHOOL.TBL_CLASS_SUB_RELN (CLASS,SUBJECT,ID) values (8,'LANG1',81);
Insert into SCHOOL.TBL_CLASS_SUB_RELN (CLASS,SUBJECT,ID) values (8,'LANG2',82);
Insert into SCHOOL.TBL_CLASS_SUB_RELN (CLASS,SUBJECT,ID) values (8,'LANG3',83);
Insert into SCHOOL.TBL_CLASS_SUB_RELN (CLASS,SUBJECT,ID) values (8,'MATHS',84);
Insert into SCHOOL.TBL_CLASS_SUB_RELN (CLASS,SUBJECT,ID) values (8,'ENV_SCIENCE',85);
Insert into SCHOOL.TBL_CLASS_SUB_RELN (CLASS,SUBJECT,ID) values (8,'HISTORY',86);
Insert into SCHOOL.TBL_CLASS_SUB_RELN (CLASS,SUBJECT,ID) values (8,'GEOGRAPHY',87);
Insert into SCHOOL.TBL_CLASS_SUB_RELN (CLASS,SUBJECT,ID) values (9,'LANG1',91);
Insert into SCHOOL.TBL_CLASS_SUB_RELN (CLASS,SUBJECT,ID) values (9,'LANG2',92);
Insert into SCHOOL.TBL_CLASS_SUB_RELN (CLASS,SUBJECT,ID) values (9,'PHY_SC',93);
Insert into SCHOOL.TBL_CLASS_SUB_RELN (CLASS,SUBJECT,ID) values (9,'LIFE_SC',94);
Insert into SCHOOL.TBL_CLASS_SUB_RELN (CLASS,SUBJECT,ID) values (9,'MATHS',95);
Insert into SCHOOL.TBL_CLASS_SUB_RELN (CLASS,SUBJECT,ID) values (9,'HISTORY',96);
Insert into SCHOOL.TBL_CLASS_SUB_RELN (CLASS,SUBJECT,ID) values (9,'GEOGRAPHY',97);
Insert into SCHOOL.TBL_CLASS_SUB_RELN (CLASS,SUBJECT,ID) values (9,'ADDITIONAL',98);
Insert into SCHOOL.TBL_CLASS_SUB_RELN (CLASS,SUBJECT,ID) values (9,'ENV_SCIENCE',99);
Insert into SCHOOL.TBL_CLASS_SUB_RELN (CLASS,SUBJECT,ID) values (10,'LANG1',101);
Insert into SCHOOL.TBL_CLASS_SUB_RELN (CLASS,SUBJECT,ID) values (10,'LANG2',102);
Insert into SCHOOL.TBL_CLASS_SUB_RELN (CLASS,SUBJECT,ID) values (10,'PHY_SC',103);
Insert into SCHOOL.TBL_CLASS_SUB_RELN (CLASS,SUBJECT,ID) values (10,'LIFE_SC',104);
Insert into SCHOOL.TBL_CLASS_SUB_RELN (CLASS,SUBJECT,ID) values (10,'MATHS',105);
Insert into SCHOOL.TBL_CLASS_SUB_RELN (CLASS,SUBJECT,ID) values (10,'HISTORY',106);
Insert into SCHOOL.TBL_CLASS_SUB_RELN (CLASS,SUBJECT,ID) values (10,'GEOGRAPHY',107);
Insert into SCHOOL.TBL_CLASS_SUB_RELN (CLASS,SUBJECT,ID) values (10,'ADDITIONAL',108);
Insert into SCHOOL.TBL_CLASS_SUB_RELN (CLASS,SUBJECT,ID) values (10,'ENV_SCIENCE',109);
Insert into SCHOOL.TBL_CLASS_SUB_RELN (CLASS,SUBJECT,ID) values (11,'LANG1',111);
Insert into SCHOOL.TBL_CLASS_SUB_RELN (CLASS,SUBJECT,ID) values (11,'LANG2',112);
Insert into SCHOOL.TBL_CLASS_SUB_RELN (CLASS,SUBJECT,ID) values (11,'COMP1',113);
Insert into SCHOOL.TBL_CLASS_SUB_RELN (CLASS,SUBJECT,ID) values (11,'COMP2',114);
Insert into SCHOOL.TBL_CLASS_SUB_RELN (CLASS,SUBJECT,ID) values (11,'COMP3',115);
Insert into SCHOOL.TBL_CLASS_SUB_RELN (CLASS,SUBJECT,ID) values (11,'OPTIONAL_STUDY',116);
Insert into SCHOOL.TBL_CLASS_SUB_RELN (CLASS,SUBJECT,ID) values (11,'ENV_SCIENCE',117);
Insert into SCHOOL.TBL_CLASS_SUB_RELN (CLASS,SUBJECT,ID) values (12,'LANG1',121);
Insert into SCHOOL.TBL_CLASS_SUB_RELN (CLASS,SUBJECT,ID) values (12,'LANG2',122);
Insert into SCHOOL.TBL_CLASS_SUB_RELN (CLASS,SUBJECT,ID) values (12,'COMP1',123);
Insert into SCHOOL.TBL_CLASS_SUB_RELN (CLASS,SUBJECT,ID) values (12,'COMP2',124);
Insert into SCHOOL.TBL_CLASS_SUB_RELN (CLASS,SUBJECT,ID) values (12,'COMP3',125);
Insert into SCHOOL.TBL_CLASS_SUB_RELN (CLASS,SUBJECT,ID) values (12,'OPTIONAL_STUDY',126);
Insert into SCHOOL.TBL_CLASS_SUB_RELN (CLASS,SUBJECT,ID) values (12,'ENV_SCIENCE',127);
REM INSERTING into SCHOOL.TBL_STD_ACA_PERF_HIST
SET DEFINE OFF;
REM INSERTING into SCHOOL.TBL_STD_ATTND
SET DEFINE OFF;
REM INSERTING into SCHOOL.TBL_STD_CURR_STD
SET DEFINE OFF;
Insert into SCHOOL.TBL_STD_CURR_STD (STUDENT,ID,CLASS,SEC,ROLL_NO,STREAM,YEAR) values (31,3,0,null,1,null,2015);
REM INSERTING into SCHOOL.TBL_STD_CURR_STD_PERF
SET DEFINE OFF;
REM INSERTING into SCHOOL.TBL_STUDENT
SET DEFINE OFF;
Insert into SCHOOL.TBL_STUDENT (ID,STDNT_NAME,MOTH_NAME,CONT_NO,DOB,BPL,ID_MARK,BORAD_NAME,R_NO,MO_MP_HS,GRADE_MP_HS,SL_NO,ADM_DATE,STD_ROLL_NO,GUARD_NAME,INST_NAME,MRK_LAST_CLASS,LAST_CLASS,ADM_CLASS,ADM_SEC,RELIGION,CASTE,SEX,ML_STATUS,STREAM,SUBJECT,FEES_E_P,FEE_AMT,PRF_PHOTO,PRF_CERTI,PRF_DOB,PRF_APP_FORM,CURRENT_ADDRESS,PERMANENT_ADDRESS) values (31,'F L','M',9632587410,null,'true','I',null,0,0,null,0,to_date('21-11-15','DD-MM-RR'),1,'G',null,0,0,0,null,'Rq','S/C','male',null,null,null,null,64,null,null,null,null,21,20);
--------------------------------------------------------
--  DDL for Index CERTIFICATE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SCHOOL"."CERTIFICATE_PK" ON "SCHOOL"."TBL_CERTIFICATE" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SCHOOL" ;
--------------------------------------------------------
--  DDL for Index CERTI_FIELDS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SCHOOL"."CERTI_FIELDS_PK" ON "SCHOOL"."TBL_CERTI_FIELDS" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SCHOOL" ;
--------------------------------------------------------
--  DDL for Index CERTI_FIELDS_RELN_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SCHOOL"."CERTI_FIELDS_RELN_PK" ON "SCHOOL"."TBL_CERTI_FIELDS_RELN" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SCHOOL" ;
--------------------------------------------------------
--  DDL for Index CERTI_FIELD_VALUES_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SCHOOL"."CERTI_FIELD_VALUES_PK" ON "SCHOOL"."TBL_CERTI_FIELD_VALUES" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SCHOOL" ;
--------------------------------------------------------
--  DDL for Index TBL_ADDRESS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SCHOOL"."TBL_ADDRESS_PK" ON "SCHOOL"."TBL_ADDRESS" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SCHOOL" ;
--------------------------------------------------------
--  DDL for Index TBL_ATTND_CLNDR_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SCHOOL"."TBL_ATTND_CLNDR_PK" ON "SCHOOL"."TBL_ATTND_CLNDR" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SCHOOL" ;
--------------------------------------------------------
--  DDL for Index TBL_CLASS_SUB_RELN_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SCHOOL"."TBL_CLASS_SUB_RELN_PK" ON "SCHOOL"."TBL_CLASS_SUB_RELN" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SCHOOL" ;
--------------------------------------------------------
--  DDL for Index TBL_STD_ACA_PERF_HIST_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SCHOOL"."TBL_STD_ACA_PERF_HIST_PK" ON "SCHOOL"."TBL_STD_ACA_PERF_HIST" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SCHOOL" ;
--------------------------------------------------------
--  DDL for Index TBL_STD_ATTND_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SCHOOL"."TBL_STD_ATTND_PK" ON "SCHOOL"."TBL_STD_ATTND" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SCHOOL" ;
--------------------------------------------------------
--  DDL for Index TBL_STD_CURR_STD_PERF_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SCHOOL"."TBL_STD_CURR_STD_PERF_PK" ON "SCHOOL"."TBL_STD_CURR_STD_PERF" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SCHOOL" ;
--------------------------------------------------------
--  DDL for Index TBL_STD_CURR_STD_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SCHOOL"."TBL_STD_CURR_STD_PK" ON "SCHOOL"."TBL_STD_CURR_STD" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SCHOOL" ;
--------------------------------------------------------
--  DDL for Index TBL_STUDENT_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SCHOOL"."TBL_STUDENT_PK" ON "SCHOOL"."TBL_STUDENT" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SCHOOL" ;
--------------------------------------------------------
--  Constraints for Table TBL_ADDRESS
--------------------------------------------------------

  ALTER TABLE "SCHOOL"."TBL_ADDRESS" ADD CONSTRAINT "TBL_ADDRESS_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SCHOOL"  ENABLE;
  ALTER TABLE "SCHOOL"."TBL_ADDRESS" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table TBL_ATTND_CLNDR
--------------------------------------------------------

  ALTER TABLE "SCHOOL"."TBL_ATTND_CLNDR" ADD CONSTRAINT "TBL_ATTND_CLNDR_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SCHOOL"  ENABLE;
  ALTER TABLE "SCHOOL"."TBL_ATTND_CLNDR" MODIFY ("CLASS" NOT NULL ENABLE);
  ALTER TABLE "SCHOOL"."TBL_ATTND_CLNDR" MODIFY ("MONTH" NOT NULL ENABLE);
  ALTER TABLE "SCHOOL"."TBL_ATTND_CLNDR" MODIFY ("YEAR" NOT NULL ENABLE);
  ALTER TABLE "SCHOOL"."TBL_ATTND_CLNDR" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table TBL_CERTIFICATE
--------------------------------------------------------

  ALTER TABLE "SCHOOL"."TBL_CERTIFICATE" MODIFY ("CERTI_NAME" NOT NULL ENABLE);
  ALTER TABLE "SCHOOL"."TBL_CERTIFICATE" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "SCHOOL"."TBL_CERTIFICATE" ADD CONSTRAINT "CERTIFICATE_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SCHOOL"  ENABLE;
--------------------------------------------------------
--  Constraints for Table TBL_CERTI_FIELDS
--------------------------------------------------------

  ALTER TABLE "SCHOOL"."TBL_CERTI_FIELDS" MODIFY ("FIELD_NAME" NOT NULL ENABLE);
  ALTER TABLE "SCHOOL"."TBL_CERTI_FIELDS" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "SCHOOL"."TBL_CERTI_FIELDS" ADD CONSTRAINT "CERTI_FIELDS_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SCHOOL"  ENABLE;
--------------------------------------------------------
--  Constraints for Table TBL_CERTI_FIELDS_RELN
--------------------------------------------------------

  ALTER TABLE "SCHOOL"."TBL_CERTI_FIELDS_RELN" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "SCHOOL"."TBL_CERTI_FIELDS_RELN" ADD CONSTRAINT "CERTI_FIELDS_RELN_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SCHOOL"  ENABLE;
--------------------------------------------------------
--  Constraints for Table TBL_CERTI_FIELD_VALUES
--------------------------------------------------------

  ALTER TABLE "SCHOOL"."TBL_CERTI_FIELD_VALUES" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "SCHOOL"."TBL_CERTI_FIELD_VALUES" ADD CONSTRAINT "CERTI_FIELD_VALUES_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SCHOOL"  ENABLE;
--------------------------------------------------------
--  Constraints for Table TBL_CLASS_SUB_RELN
--------------------------------------------------------

  ALTER TABLE "SCHOOL"."TBL_CLASS_SUB_RELN" ADD CONSTRAINT "TBL_CLASS_SUB_RELN_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SCHOOL"  ENABLE;
  ALTER TABLE "SCHOOL"."TBL_CLASS_SUB_RELN" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "SCHOOL"."TBL_CLASS_SUB_RELN" MODIFY ("SUBJECT" NOT NULL ENABLE);
  ALTER TABLE "SCHOOL"."TBL_CLASS_SUB_RELN" MODIFY ("CLASS" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table TBL_STD_ACA_PERF_HIST
--------------------------------------------------------

  ALTER TABLE "SCHOOL"."TBL_STD_ACA_PERF_HIST" ADD CONSTRAINT "TBL_STD_ACA_PERF_HIST_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SCHOOL"  ENABLE;
  ALTER TABLE "SCHOOL"."TBL_STD_ACA_PERF_HIST" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "SCHOOL"."TBL_STD_ACA_PERF_HIST" MODIFY ("YEAR" NOT NULL ENABLE);
  ALTER TABLE "SCHOOL"."TBL_STD_ACA_PERF_HIST" MODIFY ("MARKS" NOT NULL ENABLE);
  ALTER TABLE "SCHOOL"."TBL_STD_ACA_PERF_HIST" MODIFY ("SEMESTER" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table TBL_STD_ATTND
--------------------------------------------------------

  ALTER TABLE "SCHOOL"."TBL_STD_ATTND" ADD CONSTRAINT "TBL_STD_ATTND_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SCHOOL"  ENABLE;
  ALTER TABLE "SCHOOL"."TBL_STD_ATTND" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table TBL_STD_CURR_STD
--------------------------------------------------------

  ALTER TABLE "SCHOOL"."TBL_STD_CURR_STD" ADD CONSTRAINT "TBL_STD_CURR_STD_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SCHOOL"  ENABLE;
  ALTER TABLE "SCHOOL"."TBL_STD_CURR_STD" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "SCHOOL"."TBL_STD_CURR_STD" MODIFY ("CLASS" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table TBL_STD_CURR_STD_PERF
--------------------------------------------------------

  ALTER TABLE "SCHOOL"."TBL_STD_CURR_STD_PERF" ADD CONSTRAINT "TBL_STD_CURR_STD_PERF_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SCHOOL"  ENABLE;
  ALTER TABLE "SCHOOL"."TBL_STD_CURR_STD_PERF" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "SCHOOL"."TBL_STD_CURR_STD_PERF" MODIFY ("MARKS" NOT NULL ENABLE);
  ALTER TABLE "SCHOOL"."TBL_STD_CURR_STD_PERF" MODIFY ("SUB_CODE" NOT NULL ENABLE);
  ALTER TABLE "SCHOOL"."TBL_STD_CURR_STD_PERF" MODIFY ("SEMESTER" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table TBL_STUDENT
--------------------------------------------------------

  ALTER TABLE "SCHOOL"."TBL_STUDENT" ADD CONSTRAINT "TBL_STUDENT_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SCHOOL"  ENABLE;
  ALTER TABLE "SCHOOL"."TBL_STUDENT" MODIFY ("BPL" NOT NULL ENABLE);
  ALTER TABLE "SCHOOL"."TBL_STUDENT" MODIFY ("SEX" NOT NULL ENABLE);
  ALTER TABLE "SCHOOL"."TBL_STUDENT" MODIFY ("CASTE" NOT NULL ENABLE);
  ALTER TABLE "SCHOOL"."TBL_STUDENT" MODIFY ("RELIGION" NOT NULL ENABLE);
  ALTER TABLE "SCHOOL"."TBL_STUDENT" MODIFY ("ADM_CLASS" NOT NULL ENABLE);
  ALTER TABLE "SCHOOL"."TBL_STUDENT" MODIFY ("GUARD_NAME" NOT NULL ENABLE);
  ALTER TABLE "SCHOOL"."TBL_STUDENT" MODIFY ("STD_ROLL_NO" NOT NULL ENABLE);
  ALTER TABLE "SCHOOL"."TBL_STUDENT" MODIFY ("SL_NO" NOT NULL ENABLE);
  ALTER TABLE "SCHOOL"."TBL_STUDENT" MODIFY ("CONT_NO" NOT NULL ENABLE);
  ALTER TABLE "SCHOOL"."TBL_STUDENT" MODIFY ("STDNT_NAME" NOT NULL ENABLE);
  ALTER TABLE "SCHOOL"."TBL_STUDENT" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table TBL_CERTI_FIELDS_RELN
--------------------------------------------------------

  ALTER TABLE "SCHOOL"."TBL_CERTI_FIELDS_RELN" ADD CONSTRAINT "CERTI_FIELDS_RELN_CERTIFI_FK1" FOREIGN KEY ("CERTIFICATE")
	  REFERENCES "SCHOOL"."TBL_CERTIFICATE" ("ID") ON DELETE CASCADE ENABLE;
  ALTER TABLE "SCHOOL"."TBL_CERTI_FIELDS_RELN" ADD CONSTRAINT "CERTI_FIELDS_RELN_CERTI_F_FK1" FOREIGN KEY ("CERTI_FIELDS")
	  REFERENCES "SCHOOL"."TBL_CERTI_FIELDS" ("ID") ON DELETE CASCADE ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table TBL_CERTI_FIELD_VALUES
--------------------------------------------------------

  ALTER TABLE "SCHOOL"."TBL_CERTI_FIELD_VALUES" ADD CONSTRAINT "CERTI_FIELD_VALUES_CERTI__FK1" FOREIGN KEY ("CERTI_FIELD_RELN")
	  REFERENCES "SCHOOL"."TBL_CERTI_FIELDS_RELN" ("ID") ON DELETE CASCADE ENABLE;
  ALTER TABLE "SCHOOL"."TBL_CERTI_FIELD_VALUES" ADD CONSTRAINT "CERTI_FIELD_VALUES_TBL_ST_FK1" FOREIGN KEY ("STUDENT")
	  REFERENCES "SCHOOL"."TBL_STUDENT" ("ID") ON DELETE CASCADE ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table TBL_STD_ACA_PERF_HIST
--------------------------------------------------------

  ALTER TABLE "SCHOOL"."TBL_STD_ACA_PERF_HIST" ADD CONSTRAINT "TBL_STD_ACA_PERF_HIST_TBL_FK1" FOREIGN KEY ("STUDENT")
	  REFERENCES "SCHOOL"."TBL_STUDENT" ("ID") ON DELETE CASCADE ENABLE;
  ALTER TABLE "SCHOOL"."TBL_STD_ACA_PERF_HIST" ADD CONSTRAINT "TBL_STD_ACA_PERF_HIST_TBL_FK2" FOREIGN KEY ("SUB_CODE")
	  REFERENCES "SCHOOL"."TBL_CLASS_SUB_RELN" ("ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table TBL_STD_ATTND
--------------------------------------------------------

  ALTER TABLE "SCHOOL"."TBL_STD_ATTND" ADD CONSTRAINT "TBL_STD_ATTND_TBL_ATTND_C_FK1" FOREIGN KEY ("ATT_CAL")
	  REFERENCES "SCHOOL"."TBL_ATTND_CLNDR" ("ID") ON DELETE CASCADE ENABLE;
  ALTER TABLE "SCHOOL"."TBL_STD_ATTND" ADD CONSTRAINT "TBL_STD_ATTND_TBL_STUDENT_FK1" FOREIGN KEY ("STUDENT")
	  REFERENCES "SCHOOL"."TBL_STUDENT" ("ID") ON DELETE CASCADE ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table TBL_STD_CURR_STD
--------------------------------------------------------

  ALTER TABLE "SCHOOL"."TBL_STD_CURR_STD" ADD CONSTRAINT "TBL_STD_CURR_STD_TBL_STUD_FK1" FOREIGN KEY ("STUDENT")
	  REFERENCES "SCHOOL"."TBL_STUDENT" ("ID") ON DELETE CASCADE ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table TBL_STD_CURR_STD_PERF
--------------------------------------------------------

  ALTER TABLE "SCHOOL"."TBL_STD_CURR_STD_PERF" ADD CONSTRAINT "TBL_STD_CURR_STD_PERF_TBL_FK1" FOREIGN KEY ("STUDENT")
	  REFERENCES "SCHOOL"."TBL_STUDENT" ("ID") ON DELETE CASCADE ENABLE;
  ALTER TABLE "SCHOOL"."TBL_STD_CURR_STD_PERF" ADD CONSTRAINT "TBL_STD_CURR_STD_PERF_TBL_FK2" FOREIGN KEY ("SUB_CODE")
	  REFERENCES "SCHOOL"."TBL_CLASS_SUB_RELN" ("ID") ON DELETE CASCADE ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table TBL_STUDENT
--------------------------------------------------------

  ALTER TABLE "SCHOOL"."TBL_STUDENT" ADD CONSTRAINT "TBL_STUDENT_TBL_ADDRESS_FK1" FOREIGN KEY ("CURRENT_ADDRESS")
	  REFERENCES "SCHOOL"."TBL_ADDRESS" ("ID") ON DELETE CASCADE ENABLE;
  ALTER TABLE "SCHOOL"."TBL_STUDENT" ADD CONSTRAINT "TBL_STUDENT_TBL_ADDRESS_FK2" FOREIGN KEY ("PERMANENT_ADDRESS")
	  REFERENCES "SCHOOL"."TBL_ADDRESS" ("ID") ENABLE;
--------------------------------------------------------
--  DDL for Trigger TRIG_ATTND_CLNDR
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "SCHOOL"."TRIG_ATTND_CLNDR" 
before insert on tbl_attnd_clndr
for each row
    WHEN (new.id is null) declare
v_id tbl_attnd_clndr.id%type;
begin
select seq_attnd_clndr.NEXTVAL into v_id from dual;
:new.id := v_id;
end;
/
ALTER TRIGGER "SCHOOL"."TRIG_ATTND_CLNDR" ENABLE;
--------------------------------------------------------
--  DDL for Trigger TRIG_CERTIFICATE
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "SCHOOL"."TRIG_CERTIFICATE" 
before insert on tbl_certificate
for each row
    WHEN (new.id is null) declare
v_id tbl_certificate.id%type;
begin
select seq_certificate.NEXTVAL into v_id from dual;
:new.id := v_id;
end;
/
ALTER TRIGGER "SCHOOL"."TRIG_CERTIFICATE" ENABLE;
--------------------------------------------------------
--  DDL for Trigger TRIG_CERTI_FIELDS
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "SCHOOL"."TRIG_CERTI_FIELDS" 
before insert on tbl_certi_fields
for each row
    WHEN (new.id is null) declare
v_id tbl_certi_fields.id%type;
begin
select seq_certi_fields.NEXTVAL into v_id from dual;
:new.id := v_id;
end;
/
ALTER TRIGGER "SCHOOL"."TRIG_CERTI_FIELDS" ENABLE;
--------------------------------------------------------
--  DDL for Trigger TRIG_CERTI_FIELDS_RELN
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "SCHOOL"."TRIG_CERTI_FIELDS_RELN" 
before insert on tbl_certi_fields_reln
for each row
    WHEN (new.id is null) declare
v_id tbl_certi_fields_reln.id%type;
begin
select seq_certi_fields_reln.NEXTVAL into v_id from dual;
:new.id := v_id;
end;
/
ALTER TRIGGER "SCHOOL"."TRIG_CERTI_FIELDS_RELN" ENABLE;
--------------------------------------------------------
--  DDL for Trigger TRIG_CERTI_FIELD_VALUES
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "SCHOOL"."TRIG_CERTI_FIELD_VALUES" 
before insert on tbl_certi_field_values
for each row
    WHEN (new.id is null) declare
v_id tbl_certi_field_values.id%type;
begin
select seq_certi_field_values.NEXTVAL into v_id from dual;
:new.id := v_id;
end;
/
ALTER TRIGGER "SCHOOL"."TRIG_CERTI_FIELD_VALUES" ENABLE;
--------------------------------------------------------
--  DDL for Trigger TRIG_INSERT_TBL_STD_CURR_STD
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "SCHOOL"."TRIG_INSERT_TBL_STD_CURR_STD" 
after insert on tbl_student
for each row
declare
v_seq_no tbl_std_curr_std.id%type;
v_year tbl_std_curr_std.year%type;
begin
select to_char(sysdate,'YYYY') into v_year from dual;
insert into tbl_std_curr_std(student,class,sec,roll_no,stream,year) values(:new.id,:new.adm_class,:new.adm_sec,:new.std_roll_no,:new.stream,v_year);
end;
/
ALTER TRIGGER "SCHOOL"."TRIG_INSERT_TBL_STD_CURR_STD" ENABLE;
--------------------------------------------------------
--  DDL for Trigger TRIG_INSERT_TBL_STD_PERF_HIST
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "SCHOOL"."TRIG_INSERT_TBL_STD_PERF_HIST" 
after insert on tbl_std_curr_std_perf
for each row
declare
v_date tbl_std_aca_perf_hist.year%type;
begin
select to_char(sysdate,'YYYY') into v_date from dual;
insert into tbl_std_aca_perf_hist(student,sub_code,semester,marks,year,promotion,remarks) values(:new.student,:new.sub_code,:new.semester,:new.marks,v_date,null,null);
end;
/
ALTER TRIGGER "SCHOOL"."TRIG_INSERT_TBL_STD_PERF_HIST" ENABLE;
--------------------------------------------------------
--  DDL for Trigger TRIG_STD_ACA_PERF_HIST
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "SCHOOL"."TRIG_STD_ACA_PERF_HIST" 
before insert on tbl_std_aca_perf_hist
for each row
    WHEN (new.id is null) declare
v_id tbl_std_aca_perf_hist.id%type;
begin
select seq_std_aca_perf_hist.NEXTVAL into v_id from dual;
:new.id := v_id;
end;
/
ALTER TRIGGER "SCHOOL"."TRIG_STD_ACA_PERF_HIST" ENABLE;
--------------------------------------------------------
--  DDL for Trigger TRIG_STD_ATTND
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "SCHOOL"."TRIG_STD_ATTND" 
before insert on tbl_std_attnd
for each row
    WHEN (new.id is null) declare
v_id tbl_std_attnd.id%type;
begin
select seq_std_attnd.NEXTVAL into v_id from dual;
:new.id := v_id;
end;
/
ALTER TRIGGER "SCHOOL"."TRIG_STD_ATTND" ENABLE;
--------------------------------------------------------
--  DDL for Trigger TRIG_STD_CURR_STD
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "SCHOOL"."TRIG_STD_CURR_STD" 
before insert on tbl_std_curr_std
for each row
    WHEN (new.id is null) declare
v_id tbl_std_curr_std.id%type;
begin
select seq_std_curr_std.NEXTVAL into v_id from dual;
:new.id := v_id;
end;
/
ALTER TRIGGER "SCHOOL"."TRIG_STD_CURR_STD" ENABLE;
--------------------------------------------------------
--  DDL for Trigger TRIG_STD_CURR_STD_PERF
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "SCHOOL"."TRIG_STD_CURR_STD_PERF" 
before insert on tbl_std_curr_std_perf
for each row
    WHEN (new.id is null) declare
v_id tbl_std_curr_std_perf.id%type;
begin
select seq_std_curr_std_perf.NEXTVAL into v_id from dual;
:new.id := v_id;
end;
/
ALTER TRIGGER "SCHOOL"."TRIG_STD_CURR_STD_PERF" ENABLE;
--------------------------------------------------------
--  DDL for Trigger TRIG_STUDENT
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "SCHOOL"."TRIG_STUDENT" 
before insert on tbl_student
for each row
    WHEN (new.id is null) declare
v_id tbl_student.id%type;
begin
select seq_student.NEXTVAL into v_id from dual;
:new.id := v_id;
end;
/
ALTER TRIGGER "SCHOOL"."TRIG_STUDENT" ENABLE;
--------------------------------------------------------
--  DDL for Trigger TRIG_address
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "SCHOOL"."TRIG_address" 
before insert on tbl_address
for each row
    WHEN (new.id is null) declare
v_id tbl_address.id%type;
begin
select seq_address.NEXTVAL into v_id from dual;
:new.id := v_id;
end;
/
ALTER TRIGGER "SCHOOL"."TRIG_address" ENABLE;
--------------------------------------------------------
--  DDL for Function FUN_GEN_ROLL_NO
--------------------------------------------------------

  CREATE OR REPLACE FUNCTION "SCHOOL"."FUN_GEN_ROLL_NO" 
(v_section in tbl_student.adm_sec%type,
v_class in tbl_student.adm_class%type)
return number
is
v_no tbl_student.std_roll_no%type;
v_roll_no tbl_student.std_roll_no%type;
begin
select max(std_roll_no) into v_no from tbl_student where adm_class=v_class and adm_sec=v_section;
if v_no is null then
v_roll_no:=1;
else
v_roll_no:=v_no+1;
end if;
return v_roll_no;
end;

/
--------------------------------------------------------
--  DDL for Procedure GEN_ROLL_NO
--------------------------------------------------------
set define off;

  CREATE OR REPLACE PROCEDURE "SCHOOL"."GEN_ROLL_NO" 
(v_section in tbl_student.adm_sec%type,
v_class in tbl_student.adm_class%type,
v_roll_no out tbl_student.std_roll_no%type)
is
v_no tbl_student.std_roll_no%type;
begin
select max(std_roll_no) into v_no from tbl_student where adm_class=v_class and adm_sec=v_section;
v_roll_no:=v_no+1;
exception
when no_data_found then
v_roll_no:=1;
end;

/
--------------------------------------------------------
--  DDL for Synonymn DUAL
--------------------------------------------------------

  CREATE OR REPLACE PUBLIC SYNONYM "DUAL" FOR "SYS"."DUAL";
